# Generated by Django 4.2.30 on 2026-06-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
